apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PV}
spec:
  storageClassName: "nfs"
  capacity:
    storage: 100Gi
  accessModes:
  - ${MODE}
  nfs:
    path: /${PV}
    server: ${PRIMARY_IP}
  persistentVolumeReclaimPolicy: Recycle
