---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: localstorage-disks-block
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  storageClassDevices:
  - devicePaths:
          - /dev/vdb
          - /dev/vdc
          - /dev/vdd
          - /dev/vde
          - /dev/vdf
    fsType: xfs
    storageClassName: localstorage-sc-block
    volumeMode: Block
