---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rh-lab"
  namespace: "rh-lab"
spec:
  baseDomain: "e2e.bos.redhat.com"
  pullSecretRef:
    name: "rh-lab-pull-secret"
  clusterImageSetNameRef: "img4.10.5-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD0IFmpMQHlk87299njLxEgMJ3BAVN0zXlPQvE/vT1rHrluD+/vosXNdpzCEMSd3VQHduzXTOhNxYYAEgL3vy9EgCWnofJ96aPTLUz6aNdviltkfwtn8npPQ7ojnsa02ATHUjqI5ZbiQo2BcJScx3bEr/nvlczcuV6QF0EmKTPAEYRM1QQtE3TpozEAjOzElQkMepZc+RxI9k3HoSlWRiZK9o2mu96Y+aaCs9hXlmiYL7fbPVMnN83U3NMAAGqzUXT0QXjdVIuxEEvRYX2vE4LqjAopmTvfLy6c3VvO88w/0nbabQCoiWSTkZ/Wh4Pv0WVAyuahnr99sURQ5j2Zmd2f jparrill@xenomorph.localdomain"
  clusters:
  - clusterName: "edge-sno-01"
    networkType: "OVNKubernetes"
    clusterLabels:
      common: true
      group-du-sno: ""
      sites : "edge-sno-01"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.19.4.192/26
    serviceNetwork:
      - 172.30.0.0/16 
    additionalNTPSources:
      - 10.19.4.197
    nodes:
      - hostName: "edge-sno-01"
        role: "master"
        bmcAddress: "idrac-virtualmedia://10.19.0.89/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "edge-sno-01-bmh-secret"
        bootMACAddress: "A0:36:9F:D3:EC:0C"
        bootMode: "UEFI"
        rootDeviceHints:
          hctl: '0:1:0'
        nodeNetwork:
          interfaces:
            - name: enp3s0f0
              macAddress: "A0:36:9F:D3:EC:0C"
            - name: enp3s0f1
              macAddress: "A0:36:9F:D3:EC:0D"
          config:
            interfaces:
              - name: enp3s0f0
                type: ethernet
                state: up
                macAddress: "A0:36:9F:D3:EC:0C"
                ipv4:
                  enabled: true
                  dhcp: true
                  auto-dns: false
                ipv6:
                  enabled: false
              - name: enp3s0f1
                type: ethernet
                state: down
                macAddress: "A0:36:9F:D3:EC:0D"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                - edge-sno-01.e2e.bos.redhat.com
                server:
                - 10.19.4.80
  - clusterName: "edge-sno-02"
    networkType: "OVNKubernetes"
    clusterLabels:
      common: true
      group-du-sno: ""
      sites : "edge-sno-02"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.19.4.192/26
    serviceNetwork:
      - 172.30.0.0/16 
    additionalNTPSources:
      - 10.19.4.197
    nodes:
      - hostName: "edge-sno-02"
        role: "master"
        bmcAddress: "idrac-virtualmedia://10.19.0.90/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "edge-sno-02-bmh-secret"
        bootMACAddress: "A0:36:9F:D3:EC:B4"
        bootMode: "UEFI"
        nodeNetwork:
          interfaces:
            - name: enp3s0f0
              macAddress: "A0:36:9F:D3:EC:B4"
            - name: enp3s0f1
              macAddress: "A0:36:9F:D3:EC:B5"
          config:
            interfaces:
              - name: enp3s0f0
                type: ethernet
                state: up
                macAddress: "A0:36:9F:D3:EC:B4"
                ipv4:
                  enabled: true
                  dhcp: true
                  auto-dns: false
                ipv6:
                  enabled: false
              - name: enp3s0f1
                type: ethernet
                state: down
                macAddress: "A0:36:9F:D3:EC:B5"
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                - edge-sno-02.e2e.bos.redhat.com
                server:
                - 10.19.4.80
