---
apiVersion: v1
kind: Secret
metadata:
  name: SPOKE_NAMESPACE-pull-secret
  namespace: SPOKE_NAMESPACE
stringData:
  .dockerconfigjson: PULL_SECRET_STRING 
  type: kubernetes.io/dockerconfigjson

